config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :payments, only: [:index, :new, :create]

  root to: "home#index"
end

app/models/balance_change.rb
class BalanceChange < ActiveRecord::Base
  belongs_to :user
  belongs_to :payment

  validates :user, presence: true
  validates :payment, presence: true
  validates :change, presence: true, numericality: true

  after_create :update_user_balance!

  private

  def update_user_balance!
    user.update_balance!
  end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  has_many :balance_changes, inverse_of: :payment

  accepts_nested_attributes_for :balance_changes, reject_if: :reject_empty

  validates :title, presence: true
  validates :creator, presence: true

  after_create :create_payer_balance_change

  private

  def create_payer_balance_change
    sum = balance_changes.sum(:change).abs
    balance_changes.create!(user: creator, change: sum)
  end

  def reject_empty(attributes)
    attributes[:change].blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :payments, foreign_key: "creator_id"
  has_many :balance_changes

  validates :balance, presence: true

  # dodalam validacje dzieki temu latwiej bedzie pokazac im pozytywny i negatywny scenariusz dla create i update
  validates :first_name, presence: true

  def update_balance!
    update!(balance: balance_changes(true).sum(:change))
  end
end

app/controllers/api/v1/base_controller.rb
module Api
  module V1
    class BaseController < ApplicationController
      # Disables CSRF protection
      skip_before_action :verify_authenticity_token
      # before_action :authenticate_api_with_token! # TODO
    end
  end
end

app/controllers/api/v1/payments_controller.rb
module Api
  module V1
    class PaymentsController < Api::V1::BaseController
      def index
        payments = Payment.all
        payments = payments.map do |payment|
          ::V1::PaymentRepresenter.new(payment).basic
        end
        render json: payments
      end

      def create
        payment = Payment.new(payment_params)
        balance_changes_params.each do |bc|
          payment.balance_changes.new(bc)
        end
        payment.save!
        render json: ::V1::PaymentRepresenter.new(payment).basic, status: 201
      end

      private

      def payment_params
        params.permit(:title, :creator_id)
      end

      def balance_changes_params
        params.permit(balance_changes: [:user_id, :change]).fetch("balance_changes")
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < Api::V1::BaseController
      def index
        users = User.all
        users = users.map do |user|
          ::V1::UserRepresenter.new(user).basic
        end
        render json: users
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @payment = Payment.new
    User.find_each do |user|
      @payment.balance_changes.new(user: user)
    end
  end

  def index
    @payments = Payment.all
    @users = User.all
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.balance_changes.each do |bc|
      bc.change = -(bc.change.abs)
    end

    if @payment.save
      redirect_to payments_path
    else
      render :new
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:title, :creator_id, balance_changes_attributes: [:user_id, :change])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to users_path
  end

  def destroy
    user.destroy
    redirect_to users_path
  end

  def edit
    user
  end

  def update
    user.update(user_params)
    redirect_to users_path
  end

  def show
    user
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :balance)
  end

  def user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div ng-view=""></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="szama">
<head>
  <title>SzamaPwr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul>
  <li>
    <a ng-href="#/payments">
      Payments
    </a>
  </li>
</ul>

<%= yield %>

</body>
</html>

app/views/payments/index.html.erb
<h1>Payments</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Creator</th>
      <th>Balance changes</th>
    </tr>
  </thead>
  <tbody>
    <% @payments.each do |p| %>
      <tr>
        <td><%= p.title %></td>
        <td><%= p.creator.first_name %></td>
        <td>
          <ul>
            <% p.balance_changes.each do |bc| %>
              <li><%= bc.user.first_name %> : <%= bc.change %></li>
            <% end %>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New payment", new_payment_path %>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Balance</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
      <tr>
        <td><%= u.first_name %></td>
        <td><%= u.balance %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>AngularJS</h1>

<div ng-controller="PaymentsCtrl">
  <h3>Users</h3>
  <ul>
    <li ng-repeat="user in users"><div user-data="user"></div></li>
  </ul>

  <h3>Payments</h3>
  <table>
    <thead>
      <th>Title</th>
      <th>Creator</th>
      <th>Balance changes</th>
    </thead>
    <tbody>
      <tr payment-data="payment" users="users" ng-repeat="payment in payments">
      </tr>
    </tbody>
  </table>

  <form ng-submit="addNewPayment()">
    <input ng-model="newPayment.title" placeholder="Title">
    <br>
    <select ng-model="newPayment.creator_id" ng-options="userID as user.name for (userID, user) in users">
    </select> Author
    <br>
    <h5>Balance changes</h5>
    <ul>
      <li ng-repeat="(userID, user) in users">
        {{ user.name }} <input ng-model="newPayment.balance_changes[userID]">
      </li>
    </ul>

    <input type="submit" ng-disabled="!newPayment.creator_id || !newPayment.title">
  </form>
</div>

app/views/payments/new.html.erb
<%= form_for @payment do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br />

  <%= f.label :creator %>
  <%= f.collection_select(:creator_id, User.all, :id, :first_name) %><br />

  <h3>Balance changes</h3>
  <%= f.fields_for :balance_changes do |ff| %>
    <%= ff.hidden_field :user_id %>
    <%= ff.object.user.first_name %>
    <%= ff.text_field :change %><br />
  <% end %>

  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user do |f| -%>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.submit %>
<% end -%>

app/views/users/index.html.erb
<h1>List of users</h1>
<ul>
<% @users.each do |u| %>
  <li>
    <%= link_to u.email, user_path(u) %>
    <%= link_to "Edit", edit_user_path(u) %>
    <%= button_to "Destroy", user_path(u), method: :delete %>
  </li>
<% end %>
</ul>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<%= form_for @user do |f| -%>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.submit %>
<% end -%>

app/views/users/show.html.erb
<h1> <%= @user.first_name %> </h1>
<h3> <%= @user.email %> </h3>